plugins {
    id "com.android.application"
}

android {
    namespace "com.xuwyx.app"
    compileSdk 35

    defaultConfig {
        applicationId "com.xuwyx.app"
        minSdk 23
        targetSdk 35
        versionCode 24300
        versionName "2.43.0"
    }

    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
        }
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    lint {
        abortOnError true
        checkReleaseBuilds true
    }

    applicationVariants.configureEach { variant ->
        variant.outputs.configureEach {
            outputFileName = "Xuwyx-Case-2.43.0-${variant.buildType.name}.apk"
        }
    }
}

