name: Request Unity Personal License

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  request:
    name: Create activation request
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Unity activation request
        id: activation
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 2022.3.62f3

      - name: Upload activation request
        uses: actions/upload-artifact@v4
        with:
          name: Unity-activation-request
          path: ${{ steps.activation.outputs.filePath }}
          if-no-files-found: error

